import { IEmailListDTO } from "../dtos";

const uniqueEmailItem: IEmailListDTO = {
  _id: "1",
  isActive: true,
  isRead: false,
  created: new Date().toISOString(),
  received: new Date().toISOString(),
  sent: "",
  from: "nigerianprince@email.com",
  senderName: "Bakare Tunde",
  to: "myemail@email.com",
  cc: "ccemail1@email.com, ccemail2@email.com",
  bcc: "",
  subject: "An importan donation for you",
  subjectDetails: "REQUEST FOR ASSISTANCE-STRICTLY CONFIDENTIAL",
  body: "I am Dr. Bakare Tunde, the cousin of Nigerian Astronaut, Air Force Major Abacha Tunde...",
  priority: "1",
  type: "text",
};

const wrongEmailItem: IEmailListDTO = {
  _id: "2",
  isActive: true,
  isRead: false,
  created: new Date().toISOString(),
  received: new Date().toISOString(),
  sent: "",
  from: "nigerianprinceemail.com",
  senderName: "Bakare Tunde",
  to: "myemail@email.com",
  cc: "ccemail1@email.com, ccemail2@email.com",
  bcc: "",
  subject: "An importan donation for you",
  subjectDetails: "REQUEST FOR ASSISTANCE-STRICTLY CONFIDENTIAL",
  body: "I am Dr. Bakare Tunde, the cousin of Nigerian Astronaut, Air Force Major Abacha Tunde...",
  priority: "1",
  type: "html",
};

const emailAddress = "myemail@email.com";

const emailItemsList: IEmailListDTO[] = [
  {
    _id: "3",
    isActive: true,
    isRead: false,
    created: "2023-03-15T17:10:35.961Z",
    received: "2023-03-15T17:10:35.961Z",
    sent: "",
    from: "nigerianprince@email.com",
    senderName: "Bakare Tunde",
    to: "myemail@email.com",
    cc: "ccemail1@email.com, ccemail2@email.com",
    bcc: "",
    subject: "An importan donation for you",
    subjectDetails: "REQUEST FOR ASSISTANCE-STRICTLY CONFIDENTIAL",
    body: "I am Dr. Bakare Tunde, the cousin of Nigerian Astronaut, Air Force Major Abacha Tunde...",
    priority: "1",
    type: "text",
  },
  {
    _id: "4",
    isActive: true,
    isRead: false,
    created: "2023-03-15T17:10:35.961Z",
    received: "2023-03-15T17:10:35.961Z",
    sent: "",
    from: "nigerianprince@email.com",
    senderName: "Bakare Tunde",
    to: "myemail@email.com",
    cc: "ccemail1@email.com, ccemail2@email.com",
    bcc: "",
    subject: "An importan donation for you",
    subjectDetails: "REQUEST FOR ASSISTANCE-STRICTLY CONFIDENTIAL",
    body: "I am Dr. Bakare Tunde, the cousin of Nigerian Astronaut, Air Force Major Abacha Tunde...",
    priority: "1",
    type: "text",
  },
  {
    _id: "5",
    isActive: true,
    isRead: false,
    created: "2023-03-15T17:10:35.961Z",
    received: "2023-03-15T17:10:35.961Z",
    sent: "",
    from: "nigerianprince@email.com",
    senderName: "Bakare Tunde",
    to: "myemail@email.com",
    cc: "ccemail1@email.com, ccemail2@email.com",
    bcc: "",
    subject: "An importan donation for you",
    subjectDetails: "REQUEST FOR ASSISTANCE-STRICTLY CONFIDENTIAL",
    body: "I am Dr. Bakare Tunde, the cousin of Nigerian Astronaut, Air Force Major Abacha Tunde...",
    priority: "1",
    type: "text",
  },
  {
    _id: "6",
    isActive: true,
    isRead: false,
    created: "2023-03-15T17:10:35.961Z",
    received: "2023-03-15T17:10:35.961Z",
    sent: "",
    from: "nigerianprince@email.com",
    senderName: "Bakare Tunde",
    to: "myemail@email.com",
    cc: "ccemail1@email.com, ccemail2@email.com",
    bcc: "",
    subject: "An importan donation for you",
    subjectDetails: "REQUEST FOR ASSISTANCE-STRICTLY CONFIDENTIAL",
    body: "I am Dr. Bakare Tunde, the cousin of Nigerian Astronaut, Air Force Major Abacha Tunde...",
    priority: "1",
    type: "text",
  },
  {
    _id: "7",
    isActive: true,
    isRead: false,
    created: "2023-03-15T17:10:35.961Z",
    received: "2023-03-15T17:10:35.961Z",
    sent: "",
    from: "nigerianprince@email.com",
    senderName: "Bakare Tunde",
    to: "myemail@email.com",
    cc: "ccemail1@email.com, ccemail2@email.com",
    bcc: "",
    subject: "An importan donation for you",
    subjectDetails: "REQUEST FOR ASSISTANCE-STRICTLY CONFIDENTIAL",
    body: "I am Dr. Bakare Tunde, the cousin of Nigerian Astronaut, Air Force Major Abacha Tunde...",
    priority: "1",
    type: "text",
  },
  {
    _id: "8",
    isActive: true,
    isRead: false,
    created: "2023-03-15T17:10:35.961Z",
    received: "2023-03-15T17:10:35.961Z",
    sent: "",
    from: "nigerianprince@email.com",
    senderName: "Bakare Tunde",
    to: "myemail@email.com",
    cc: "ccemail1@email.com, ccemail2@email.com",
    bcc: "",
    subject: "An importan donation for you",
    subjectDetails: "REQUEST FOR ASSISTANCE-STRICTLY CONFIDENTIAL",
    body: "I am Dr. Bakare Tunde, the cousin of Nigerian Astronaut, Air Force Major Abacha Tunde...",
    priority: "1",
    type: "text",
  },
];

export { uniqueEmailItem, wrongEmailItem, emailItemsList, emailAddress };
